name: Merge Dependabot PR

on:
    workflow_run:
        types:
            - completed
        workflows:
            - 'CI'

jobs:
    merge-me:
        name: Merge Dependabot PR

        runs-on: ubuntu-latest

        steps:
            - name: Merge
              if: ${{ github.event.workflow_run.conclusion == 'success' }}
              uses: ridedott/merge-me-action@v2
              with:
                  GITHUB_TOKEN: ${{ secrets.MERGEME_ACTION }}
                  PRESET: DEPENDABOT_MINOR