

name: CI

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:

jobs:
  tests:
    uses: lugark/jira-metrics/.github/workflows/PhpUnit.yml@9-support-for-influxdb-2x
  codecov:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        name: Download reports-artifacts
        with:
          name: test-reports

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          files: ./coverage.xml

  sonarcloud:
    needs: tests
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        name: Download reports-artifacts
        with:
          name: test-reports

      - name: Fix coverage-reports path
        run:  sed -i 's#/home/runner/work/jira-metrics/jira-metrics#/github/workspace#g' coverage.xml; sed -i 's#/home/runner/work/jira-metrics/jira-metrics#/github/workspace#g' phpunit_report.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
