name: PhpUnit

on:
  workflow_call:


jobs:
  tests:
    name: Unittests & Coverage-Report

    env:
      PHP_EXTENSIONS: json, curl, zip
      PHP_INI_VALUES: memory_limit=-1

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2.1.5
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: pcov
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: ${{ env.PHP_INI_VALUES }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --no-interaction --no-suggest

      - name: Run unittests
        run: bin/phpunit  --coverage-clover reports/coverage.xml --log-junit reports/phpunit_report.xml

      - uses: actions/upload-artifact@v2
        name: Upload reports-artifacts
        with:
          name: test-reports
          path: reports/
          retention-days: 1
